language: node_js
node_js:
  - 8

jobs:
  include:
    - stage: lint
      script: npm run lint hateoas-navigator
    - script: npm run lint resource-components
    - script: npm run lint demo
    - stage: test
      script: npm run test hateoas-navigator
    - script: npm run test resource-components
    - script: npm run test demo
