language: node_js
node_js:
  - 10

addons:
  chrome: stable

jobs:
  include:
    - stage: lint
      script: npm run lint hateoas-navigator
      name: "hateoas-navigator"
    - script: npm run lint resource-components
      name: "resource-components"
    - script: npm run lint demo
      name: "demo"
    - stage: test
      script: npm run test hateoas-navigator
      name: "hateoas-navigator"
    - script: npm run test resource-components
      name: "resource-components"
    - script: npm run test demo
      name: "demo"
