export {ResourceComponentsModule} from './resource-components.module';
export {ResourceComponentsConfiguration} from './resource-components-configuration';
export {GenericRoutes} from './generic-routes';
export * from './resource-form';
export * from './resource-item';
export * from './resource-list';
export * from './navigation';
export * from './customizable';
export * from './message-dialog';
